`include "uvm_macros.svh"
import uvm_pkg::*;

`include "sync_fifo_if.sv"
`include "fifo_seq_item.sv"
`include "fifo_sequencer.sv"
`include "fifo_seq.sv"
`include "fifo_driver.sv"
`include "fifo_monitor.sv"
`include "fifo_scoreboard.sv"
`include "fifo_agent.sv"
`include "fifo_env.sv"
`include "fifo_basic_test.sv"
`include "fifo_rand_test.sv"
`include "fifo_prtcl_err_wr_test.sv"
`include "fifo_tb_top.sv"